Always save the most recent waker
blackbeam/mysql_async pull request #272
Opened 2023-12-19 16:13 UTC by espindola

The reason for it is in a comment. I found this by inspection, but can try to write a testcase with a dummy executor. Not sure if this issue would show up when using tokio.

2023-12-26 11:03 UTC, espindola commented
I have included a test now.

2023-12-26 18:44 UTC, blackbeam requested changes

2023-12-28 14:01 UTC, espindola commented on Cargo.toml
> +waker-fn = "1"
done

2024-01-02 12:55 UTC, espindola commented
Happy new year! Are there any other changes that you would like for this PR?

2024-01-02 18:58 UTC, merged